# Generated by Django 5.1 on 2024-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='', upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
    ]
