# Generated by Django 5.1 on 2024-09-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_image_userprofile_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='locations',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='description',
            new_name='type',
        ),
    ]
