# Generated by Django 5.1 on 2024-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_rename_locations_tour_city_rename_name_tour_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
